require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '13.0'  # This version should be >= 13.0

target 'SuprsendRnSdkExample' do
  config = use_native_modules!
  use_frameworks!

  use_react_native!(:path => config["reactNativePath"])

  pod 'suprsend-rn-sdk', :path => '../..'

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # use_flipper!({ 'Flipper' => '0.80.0' })
  # post_install do |installer|
  #   flipper_post_install(installer)
  # end
end
